{
 "title": "SDE Node Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(node_boot_time_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Up Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "CPU Usage (5m Window)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 - avg(irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[5m])) by (instance) * 100"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes)) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{device=\"rootfs\",mountpoint=\"/\"} - node_filesystem_free_bytes{device=\"rootfs\",mountpoint=\"/\"}) / node_filesystem_size_bytes{device=\"rootfs\",mountpoint=\"/\"} * 100"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "swarm_node_info" }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load1 > on (instance) 2 * count by (instance)(node_cpu_seconds_total{mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "1024 * sum by (instance) ( (rate(node_vmstat_pgpgin[1m]) + rate(node_vmstat_pgpgout[1m])))"
    }
   ]
  },
  {
   "title": "Time to fill disk (projected)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_free_bytes{device=\"rootfs\",mountpoint=\"/\"}[5m],4*3600)",
     "legendFormat": "rootfs, /"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_build_info{instance=\"$server:9100\"}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 10 },
   "format": "sci",
   "valueName": "current",
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_free_bytes{device=\"rootfs\",mountpoint=\"/\"}[5m],4*3600)"
    }
   ]
  }
 ]
}