global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - alerting.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['sscisapp9:9090']
  - job_name: 'node_exporter'
    static_configs:
    - targets: ['sscisapp9:9100','sscisapp10:9100','sscisapp11:9100']
  # - job_name: 'grafana'
  #   static_configs:
  #   - targets: ['127.0.0.1:3000']
  # - job_name: 'docker'
  #   static_configs:
  #   - targets: ['127.0.0.1:9323']
  # - job_name: 'cadvisor'
  #   static_configs:
  #   - targets: ['127.0.0.1:18080']
  # - job_name: 'traefik-docker'
  #   static_configs:
  #   - targets: ['127.0.0.1:8080']
