### docker.yml
---
- name: Copy Docker daemon.json
  copy:
    src: ./config/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
  tags:
  - docker

- name: Start Docker service
  become: true
  service:
    daemon-reload: yes
    name: docker
    state: started
    enabled: yes
  tags:
  - docker
