### yums.yml
---
- name: Install the latest version of Docker pre-requisites
  yum:
    name:
      - atomic-registries
      - audit-libs-python
      - container-selinux
      - containers-common
      - container-storage-setup
      - checkpolicy
      - device-mapper-persistent-data 
      - libcgroup
      - libsemanage-python
      - libyaml
      - lvm2
      - oci-register-machine
      - oci-systemd-hook
      - oci-umount
      - policycoreutils-python
      - python-IPy
      - python-backports
      - python-backports-ssl_match_hostname
      - python-ipaddress
      - python-setuptools
      - python-pytoml
      - PyYAML
      - subscription-manager-rhsm-certificates
      - setools-libs
      - yajl
      - yum-utils 
    state: latest

- name: Install the latest version of Docker pre-requisites
  yum:
    name:
      - docker
      - docker-common
      - docker-client 
    state: latest

# - name: Add repository
#   yum_repository:
#     name: docker
#     description: Docker CE Repository
#     baseurl: https://download.docker.com/linux/centos/docker-ce.repo
#     gpgcheck: no

# - name: Install Docker
#   yum:
#     name: 
#       - docker-ce
#     state: latest

