# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
#deleteDatasources:
#   - name: Graphite
#     orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the datbase
datasources:
-  access: 'proxy'                       # make grafana perform the requests
   editable: true                        # whether it should be editable
   is_default: true                      # whether this should be the default DS
   name: 'Prometheus'                    # name of the datasource
   org_id: 1                             # id of the organization to tie this datasource to
   type: 'prometheus'                    # type of the data source
   url: 'http://sscisapp9:9090'          # url of the prom instance
   version: 1                            # well, versioning

# datasources:
# #   # <string, required> name of the datasource. Required
# - name: Prometheus
#   type: prometheus
#   access: direct
# #   # <int> org id. will default to orgId 1 if not specified
#   orgId: 1
#   url: http://127.0.0.1:9090
#   password:
#   user:
#   database:
#   basicAuth: false
#   basicAuthUser:
#   basicAuthPassword:
#   withCredentials: false
#   isDefault: true
#   jsonData:
#      graphiteVersion: "1.1"
#      tlsAuth: false
#      tlsAuthWithCACert: false
#   secureJsonData:
#     tlsCACert: "..."
#     tlsClientCert: "..."
#     tlsClientKey: "..."
#   version: 1
#   editable: true

